name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

    build:

      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4
        - name: Install dependencies
          run: |
            # Update package lists
            sudo apt-get update
            # Install required packages
            sudo apt-get install -y \
              build-essential \
              git \
              uuid-dev \
              acpica-tools \
              nasm \
              python3 \
              python3-pip \
              curl
            # Create symbolic link for python
            sudo ln -s $(which python3) /usr/local/bin/python
            # Create artifacts folder
            mkdir artifacts
        - name: Clone latest EDK2 release
          run: |
            # Get latest release
            LATEST_RELEASE=$(curl -s "https://api.github.com/repos/tianocore/edk2/releases/latest" | grep -o '"tag_name": "[^"]*' | sed 's/"tag_name": "//')
            export LATEST_RELEASE
            echo "Latest Release: $LATEST_RELEASE"
            # Clone EDK2 repository
            git clone --depth 1 "https://github.com/tianocore/edk2.git" -b "$LATEST_RELEASE" edk2
        - name: Update submodules
          working-directory: edk2
          run: |
            # Update submodules
            git submodule update --init --recursive
        - name: Run tests
          working-directory: edk2
          run: |
            # Source edksetup script
            . ./edksetup.sh
            # Run tests
            make -C BaseTools
        - name: Build OVMF
          working-directory: edk2
          run: |
            # Source edksetup script
            . ./edksetup.sh
            IFS=', ' read -r -a TARGETS <<< "$TARGETS"
            IFS=', ' read -r -a ARCHS <<< "$ARCHS"
            IFS=', ' read -r -a DSC <<< "$DSC"
            for target in "${TARGETS[@]}"; do
              for i in "${!ARCHS[@]}"; do
                arch=${ARCHS[$i]}
                dsc=${DSC[$i]}
                echo "Building OVMF for $arch $target $dsc"
                build -a "$arch" -b "$target" -t GCC5 -p OvmfPkg/OvmfPkg"$dsc"
                cd ..
                mkdir -p artifacts/"$arch"/"$target"
                cp edk2/Build/Ovmf"$arch"/"$target"/FV/OVMF_CODE.fd artifacts/"$arch"/"$target"
                cp edk2/Build/Ovmf"$arch"/"$target"/FV/OVMF_VARS.fd artifacts/"$arch"/"$target"
                cp edk2/Build/Ovmf"$arch"/"$target"/FV/OVMF.fd artifacts/"$arch"/"$target"
                cd edk2
              done
            done
          env:
            ARCHS: IA32,X64,3264
            TARGETS: RELEASE,DEBUG,NOOPT
            DSC: Ia32,X64,Ia32X64
