name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

    build:

      runs-on: ubuntu-latest
  
      steps:
        - uses: actions/checkout@v4
        - name: Install dependencies
          run: |
            # Update package lists
            sudo apt-get update
            # Install required packages
            sudo apt-get install -y \
              build-essential \
              git \
              uuid-dev \
              acpica-tools \
              nasm \
              python3 \
              python3-pip \
              curl
            # Create symbolic link for python
            sudo ln -s $(which python3) /usr/local/bin/python
        - name: Clone latest EDK2 release
          run: |
            # Get latest release
            LATEST_RELEASE=$(curl -s "https://api.github.com/repos/tianocore/edk2/releases/latest" | grep -o '"tag_name": "[^"]*' | sed 's/"tag_name": "//')
            export LATEST_RELEASE
            echo "Latest Release: $LATEST_RELEASE"
            # Clone EDK2 repository
            git clone --depth 1 "https://github.com/tianocore/edk2.git" -b "$LATEST_RELEASE" edk2
        - name: Update submodules
          working-directory: edk2
          run: |
            # Update submodules
            git submodule update --init --recursive
        - name: Run tests
          working-directory: edk2
          run: |
            # Source edksetup script
            . ./edksetup.sh
            # Run tests
            make -C BaseTools
        - name: Build OVMF
          working-directory: edk2
          run: |
            # Source edksetup script
            . ./edksetup.sh
            # Build OVMF image
            build -a X64 -b RELEASE -t GCC5 -p OvmfPkg/OvmfPkgX64.dsc -DSECURE_BOOT_ENABLE=TRUE
